version: 2

sources:
  - name: novatrade
    database: novatrade
    schema: raw
    loaded_at_field: loaded_at
    freshness:
      warn_after:
        count: 24
        period: hour
      error_after:
        count: 48
        period: hour
    tables:
      - name: ntg_customers
        columns:
          - name: '"CustomerID"'
            data_tests: [unique, not_null]
      - name: ntg_products
        columns:
          - name: '"ProductID"'
            data_tests: [unique, not_null]
      - name: ntg_sales
        columns:
          - name: '"TransactionID"'
            data_tests: [unique, not_null]
      - name: ntg_stores
        columns:
          - name: '"StoreID"'
            data_tests: [unique, not_null]
