version: 2

sources:
  - name: novatrade
    database: novatrade
    schema: raw
    tables:
      - name: ntg_customers
        columns:
          - name: '"CustomerID"'
            data_tests: [unique, not_null]
      - name: ntg_products
        columns:
          - name: '"ProductID"'
            data_tests: [unique, not_null]
      - name: ntg_sales
        columns:
          - name: '"TransactionID"'
            data_tests: [unique, not_null]
      - name: ntg_stores
        columns:
          - name: '"StoreID"'
            data_tests: [unique, not_null]
